USE hippo_abe;
TRUNCATE Albums;

INSERT INTO Albums (artist, name, release_date, sales, genre)
VALUES ('Michael Jackson', 'Thriller', 1982, 70, 'pop'),
('AC/DC', 'Back in Black', 1980, 50, 'Hard Rock'),
('Whitney Houston', 'The Bodyguard', 1992, 45, 'R&B'),
('Pink Floyd', 'The Dark Side of the Moon', 1973, 45, 'Progressive rock'),
('Eagles', 'Their Greatest Hits (1971 -  1975)', 1976, 44, 'Soft Rock'),
('Meat Loaf', 'bat Out of Hell', 1977, 43, 'Hard Rock'),
('Eagles', 'Hotel California', 1976, 42, 'Soft Rock'),
('Shania Twain', 'Come on Over', 1997, 40, 'Country Pop'),
('Fleetwood Mac', 'Rumors', 1977, 40, 'Soft Rock'),
('Bee Gees', 'Saturday Night Fever', 1977, 40, 'Disco'),
('Led Zeppelin', 'Led Zeppelin IV', 1971, 37, 'Hard rock heavy metal'),
('Michael Jackson', 'Bad', 1987, 35, 'Pop'),
('Alanis Morissette', 'Jagged Little Pill', 1995, 33, 'Alternative Rock'),
('Various  artist', 'Dirty Dancing', 1987, 32, 'Pop Rock'),
('Celine Dion', 'Falling into You', 1996, 32, 'Pop Soft rock'),
('Adele', '21', 2011, 31, 'Pop soul'),
('The Beatles', '1', 2000, 31, 'Rock'),
('Metallica','Metallica', 1991, 31, 'Rock'),
('Celine Dion', 'Lets Talk About Love', 1997, 31, 'Pop Soft Rock'),
('Bob Marley and the Wailers', 'Legend: the Best of Bob Marley& The Wailers', 1984, 30, 'Reggae'),
('Guns N Roses', 'Appetite for Destruction', 1987, 30, 'Hard rock'),
('Bruce Springsteen', 'Born in the USA', 1984, 30, 'Heartland rock'),
('ABBA', 'Gold: Greatest Hits', 1992, 30, 'Pop Disco'),
('Dire Straits', 'Brothers in Arms', 1985, 30, 'Blues Rock'),
('Madonna', 'The Immaculate Collection', 1990, 30, 'Pop Dance'),
('Santana', 'Supernatural', 1999, 30, 'latin Rock'),
('Pink Floyd', 'The Wall', 1979, 30, 'Progressive Rock'),
('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 1967, 30, 'Rock'),
('Michael Jackson', 'Dangerous', 1991, 30, 'R&B New Jack Swing'),
('The Beatles', 'Abbey Road', 1969, 30, 'Rock');